public class automation_accountOpp {
    public static void insertion(list<opportunity> op){
        list<Account> ac =new list<Account>();
            for (opportunity opp:op){
                if(opp.amount!=null){
                    
                }
            {
                
}
        }
}
    public static void updation(){
        
    }
    public static void deletion(){
        
    }
}